#docker run -d -p 6379:6379 --name redisdb
version: "2.1"
services:
  redisdb:
    container_name: redisdb
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning # --requirepass interview12XZ
    volumes:
      - ./data/:/data
  mongodb:
    container_name: mongodb
    image: mongo:latest
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

volumes:
  data: